feat: Added invalid percent publisher.
6RiverSystems/navigation pull request #85
Opened 2018-10-01 19:46 UTC by grieneis

2018-10-02 21:49 UTC, dantwinkler commented on amcl/src/amcl/sensors/amcl_laser.cpp
> +  *percent_invalid_poses = (float)invalid_count / set->sample_count;
Not sure it's possible, but we should check for set->sample_count != 0 case.

2018-10-02 21:50 UTC, dantwinkler commented on amcl/src/amcl/sensors/amcl_laser.cpp
> +  ROS_WARN("Invalid count %d", invalid_count);
I think this should be debug or trace.  It happens a lot during normal operation.

2018-10-02 21:50 UTC, dantwinkler commented on amcl/src/amcl/sensors/amcl_laser.cpp
> +  *percent_invalid_poses = (float)invalid_count / set->sample_count;
Divide by 0 check.

2018-10-02 21:50 UTC, dantwinkler commented on amcl/src/amcl/sensors/amcl_laser.cpp
> +  *percent_invalid_poses = (float)invalid_count / set->sample_count;
Divide by 0 check.

2018-10-02 22:11 UTC, dantwinkler requested changes
Just a few divide by 0 checks.  Don't think it's possible for it to be 0 but just in case.

2018-10-04 15:08 UTC, grieneis commented
Updated based on code review.

2018-10-04 16:06 UTC, dantwinkler approved these changes

2018-10-05 15:54 UTC, merged